server:
  port: 800

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      discovery:
      #        root: /spring-cloud-service
      connect-string: 127.0.0.1:2181



  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.atguigu.springcloud.entities

