server:
  port: 8000



spring:
  application:
    name: cloud-comsul-service
  cloud:
    consul:
        host: 127.0.0.1
        port: 8500     # consul运行的端口号
        discovery:
          service-name: ${spring.application.name}

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
