server:
  port: 80

spring:
  application:
    name: cloud-openfen-service-80

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   # 集群版
ribbon:
  ReadTimeout: 5000   # 读超时时间
  connectTimeout: 5000 # 连接超时时间

logging:
  level:
    com.atguigu.springcloud.service.PaymenOpenFeignService: debug